import { Inter } from 'next/font/google';
import Provider from '@/context/Provider'
import Header from '@/components/shared/Header';
import Footer from '@/components/shared/Footer';

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function DashboardLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
        <Provider>
          <Header />
          {children}
          <Footer />
        </Provider>
  )
}
